data:
  type: image
  train_dir: /home/2000G/Dataset/ImageNet/ImageNet64/
  img_size: 64
  nlabels: 1
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 512
    embed_size: 1
discriminator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 512
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/NSGANreal0_far
  gan_type: standard
  reg_type: real
  reg_param: 10.
  batch_size: 64
  nworkers: 32
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  sample_nlabels: 20
  inception_every: 10000
  save_every: 900
  backup_every: 100000
  restart_every: -1
#  optimizer: rmsprop
  optimizer: adam
  lr_g: 0.0001
  lr_d: 0.0003
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 32
  sample_size: 15
  sample_nrow: 5
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
